#version: '3'
#
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      - VIRTUAL_HOST=your-domain.com
#      - LETSENCRYPT_HOST=your-domain.com
#      - LETSENCRYPT_EMAIL=your-email@example.com
#    ports:
#      - "8080:8080"
#    depends_on:
#      - nginx-proxy
#      - letsencrypt
#      - spring-boot-app
#      - postgres-db
#
#  nginx-proxy:
#    image: jwilder/nginx-proxy
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#      - ./nginx.conf:/etc/nginx/nginx.conf
#
#  letsencrypt:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    environment:
#      - NGINX_PROXY_CONTAINER=nginx-proxy
#
#  spring-boot-app:
#    image: muhammadtrying/tour_project
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres-db
#
#  postgres-db:
#    image: postgres
#    environment:
#      POSTGRES_DB: tour-firm-project
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: root123
#    ports:
#      - "5433:5432"


version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=visaexpert.uz
      - LETSENCRYPT_HOST=visaexpert.uz
      - LETSENCRYPT_EMAIL=muhammadtrying@gmail.com
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tour-firm-project
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root123
    ports:
      - "8080:8080"
    depends_on:
      - db

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=tour-firm-project
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: